// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'dart:async';

import 'package:example/src/biz/biz1/flutter1/route_action.dart';
import 'package:flutter_thrio/flutter_thrio.dart';

import 'home/module.dart' as home;

class Module with ThrioModule, ModuleRouteAction {
  @override
  String get key => 'flutter1';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(home.Module(), moduleContext);
  }

  @override
  void onRouteActionRegister(final ModuleContext moduleContext) {
    registerRouteAction('getPeople{intValue?}', <TParams, TResult>(
      final url,
      final action,
      final queryParams, {
      final params,
    }) async {
      final result = getPeople(
        url,
        action,
        queryParams,
        intValue: getValue<int>(params, 'intValue'),
      );
      if (result is Future<TResult?>) {
        return result as Future<TResult?>;
      } else if (result is TResult) {
        return result as TResult;
      }
      return null;
    });
  }
}
