// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter1.route_action.dart';
import 'home/module.dart' as home;

class Module with ThrioModule, ModuleRouteAction {
  @override
  void onRouteActionRegister(ModuleContext moduleContext) {
    registerRouteAction('getPeople{intValue?}', <TParams, TResult>(
      url,
      action,
      queryParams, {
      params,
    }) {
      final result = onGetPeople(
        moduleContext,
        url,
        action,
        queryParams,
        intValue: getValueOrNull<int>(params, 'intValue'),
      );
      if (result is Future<TResult?>) {
        return result as Future<TResult?>;
      } else if (result is TResult) {
        return result as TResult;
      }
      return null;
    });

    registerRouteAction('getString{boolValue}', <TParams, TResult>(
      url,
      action,
      queryParams, {
      params,
    }) {
      final result = onGetString(
        moduleContext,
        url,
        action,
        queryParams,
        boolValue: getValue<bool>(params, 'boolValue'),
      );
      if (result is Future<TResult?>) {
        return result as Future<TResult?>;
      } else if (result is TResult) {
        return result as TResult;
      }
      return null;
    });
  }

  @override
  String get key => 'flutter1';

  @override
  void onModuleRegister(ModuleContext moduleContext) {
    registerModule(home.Module(), moduleContext);
  }
}
