// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

class HomeRoute extends NavigatorRouteLeaf {
  factory HomeRoute(final NavigatorRouteNode parent) => _instance ??= HomeRoute._(parent);

  HomeRoute._(super.parent);

  static HomeRoute? _instance;

  @override
  String get name => 'home';

  Future<TPopParams> push<TParams, TPopParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorIntCallback? result,
  }) =>
      ThrioNavigator.push<TParams, TPopParams>(
        url: url,
        params: params,
        animated: animated,
        result: result,
      );
}
