// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'home/home.route.dart';

class Flutter1Route extends NavigatorRouteNode {
  factory Flutter1Route(final NavigatorRouteNode parent) => _instance ??= Flutter1Route._(parent);

  Flutter1Route._(super.parent) {
    home = HomeRoute(this);
  }

  static Flutter1Route? _instance;

  late final HomeRoute home;

  @override
  String get name => 'flutter1';

  Future<int> push<TParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorParamsCallback? poppedResult,
  }) =>
      ThrioNavigator.push(
        url: url,
        params: params,
        animated: animated,
        poppedResult: poppedResult,
      );

  /// 通知 flutter1
  ///
  Future<bool> flutter1({
    required final int intValue,
    final int index = 0,
  }) =>
      ThrioNavigator.notify(
        url: url,
        name: 'flutter1',
        params: {
          'intValue': intValue,
        },
        index: index,
      );
}
