// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter1/module.dart' as flutter1;
import 'flutter11/module.dart' as flutter11;
import 'flutter3/module.dart' as flutter3;
import 'flutter5/module.dart' as flutter5;
import 'flutter7/module.dart' as flutter7;
import 'flutter9/module.dart' as flutter9;

class Module with ThrioModule, ModuleParamScheme {
  @override
  String get key => 'biz1';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(flutter1.Module(), moduleContext);
    registerModule(flutter3.Module(), moduleContext);
    registerModule(flutter5.Module(), moduleContext);
    registerModule(flutter7.Module(), moduleContext);
    registerModule(flutter9.Module(), moduleContext);
    registerModule(flutter11.Module(), moduleContext);
  }

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme<int>('intValue');
  }
}
