// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter6.page.dart';
import 'flutter6.route_custom_handler.dart';

class Module with ThrioModule, ModuleRouteCustomHandler, ModulePageBuilder {
  @override
  void onRouteCustomHandlerRegister(final ModuleContext moduleContext) =>
      on$RouteCustomHandlerRegister(moduleContext, registerRouteCustomHandler);

  @override
  String get key => 'flutter6';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (final settings) => Flutter6Page(
            moduleContext: moduleContext,
            params: settings.params,
            url: settings.url,
            index: settings.index,
          );
}
