// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:example/src/biz/types/people.dart';
import 'package:flutter_jsonable/flutter_jsonable.dart';

/// a struct description a house.
///
class House {
  House({
    this.address = '',
    this.owner,
  });

  factory House.fromJson(final Map<String, dynamic> json) => House(
        address: getValueFromJsonOrDefault<String>(json, 'address', ''),
        owner: getValueFromJsonOrNull<People>(json, 'owner'),
      );

  factory House.from(final House other) => House.fromJson(other.toJson());

  final String address;

  final People? owner;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'address': address,
        'owner': getJsonFromValue<People>(owner),
      };
}
