// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_jsonable/flutter_jsonable.dart';

/// a struct description a people
///
class People {
  People({
    this.name = '',
    this.age = 10,
    this.sex = '',
    this.balance = 0.0,
    this.wife,
    this.aliases = const <String>[],
    this.children = const <People>[],
    this.parents = const <String, People>{},
  });

  factory People.fromJson(final Map<String, dynamic> json) => People(
        name: getValueFromJsonOrDefault<String>(json, 'name', ''),
        age: getValueFromJsonOrDefault<int>(json, 'age', 10),
        sex: getValueFromJsonOrDefault<String>(json, 'sex', ''),
        wife: getValueFromJsonOrNull<People>(json, 'wife'),
        children: getListFromJson<People>(json, 'children'),
        parents: getMapFromJson<People>(json, 'parents'),
      );

  factory People.from(final People other) => People.fromJson(other.toJson());

  final String name;

  final int age;

  final String sex;

  final double balance;

  final People? wife;

  final List<String> aliases;

  final List<People> children;

  final Map<String, People> parents;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'name': name,
        'age': age,
        'sex': sex,
        'wife': getJsonFromValue<People>(wife),
        'children': getJsonFromList(children),
        'parents': getJsonFromMap(parents),
      };
}
