// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_jsonable/flutter_jsonable.dart';

/// 结构体的注释
///
class UserProfile {
  UserProfile({
    this.uid = 2,
    this.userName = '',
    this.emailVerified = false,
    this.mobileVerified = false,
    this.userToken = '',
  });

  factory UserProfile.fromJson(Map<String, dynamic> json) => UserProfile(
        userName: getValueFromJsonOrNull<String>(json, 'userName') ?? '',
        emailVerified:
            getValueFromJsonOrNull<bool>(json, 'emailVerified') ?? false,
        mobileVerified:
            getValueFromJsonOrNull<bool>(json, 'mobileVerified') ?? false,
        userToken: getValueFromJsonOrNull<String>(json, 'userToken') ?? '',
      );

  factory UserProfile.copyWith(
    UserProfile other, {
    int? uid,
    String? userName,
    bool? emailVerified,
    bool? mobileVerified,
    String? userToken,
  }) {
    final otherJson = other.toJson();
    otherJson['userName'] = userName ?? otherJson['userName'];
    otherJson['emailVerified'] = emailVerified ?? otherJson['emailVerified'];
    otherJson['mobileVerified'] = mobileVerified ?? otherJson['mobileVerified'];
    otherJson['userToken'] = userToken ?? otherJson['userToken'];
    return UserProfile.fromJson(otherJson)..uid = uid ?? other.uid;
  }

  int uid;

  final String userName;

  final bool emailVerified;

  final bool mobileVerified;

  final String userToken;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'userName': userName,
        'emailVerified': emailVerified,
        'mobileVerified': mobileVerified,
        'userToken': userToken,
      };
}
