// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_jsonable/flutter_jsonable.dart';

/// 结构体的注释
///
class UserProfile {
  UserProfile({
    this.uid = 2,
    required this.userName,
    this.emailVerified = false,
    this.mobileVerified = false,
    required this.userToken,
  });

  factory UserProfile.fromJson(final Map<String, dynamic> json) => UserProfile(
        uid: getValueFromJsonOrDefault<int>(json, 'uid', 2),
        userName: getValueFromJsonOrNull<String>(json, 'userName'),
        emailVerified:
            getValueFromJsonOrDefault<bool>(json, 'emailVerified', false),
        mobileVerified:
            getValueFromJsonOrDefault<bool>(json, 'mobileVerified', false),
        userToken: getValueFromJsonOrNull<String>(json, 'userToken'),
      );

  final int uid;

  final String? userName;

  final bool emailVerified;

  final bool mobileVerified;

  final String? userToken;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'userName': userName,
        'emailVerified': emailVerified,
        'mobileVerified': mobileVerified,
        'userToken': userToken,
      };
}
