// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

/// 结构体的注释
///
class UserProfile {
  UserProfile({
    this.uid = 2,
    required this.userName,
    this.emailVerified = false,
    this.mobileVerified = false,
    required this.userToken,
  });

  factory UserProfile.fromMap(final Map<String, dynamic> json) => UserProfile(
        uid: getValueOrDefault<int>(json, 'uid', 2),
        userName: getValue<String>(json, 'userName'),
        emailVerified: getValueOrDefault<bool>(json, 'emailVerified', false),
        mobileVerified: getValueOrDefault<bool>(json, 'mobileVerified', false),
        userToken: getValue<String>(json, 'userToken'),
      );

  final int? uid;

  final String userName;

  final bool emailVerified;

  final bool mobileVerified;

  final String userToken;

  Map<String, dynamic> toMap() => <String, dynamic>{
        'userName': userName,
        'emailVerified': emailVerified,
        'mobileVerified': mobileVerified,
        'userToken': userToken,
      };
}
