// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'home.page.dart';

class Module with ThrioModule, ModuleParamScheme, ModulePageBuilder {
  @override
  String get key => 'home';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (final settings) => HomePage(
            moduleContext: moduleContext,
            params: settings.params,
            url: settings.url,
            index: settings.index,
          );

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme('stringKeyBiz1');
  }
}
