// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'biz1/biz1.route.dart';
import 'biz2/biz2.route.dart';

final root = _Route();

class _Route extends NavigatorRouteNode {
  factory _Route() => _instance ??= _Route._();

  _Route._() : super.home() {
    biz1 = Biz1Route(this);
    biz2 = Biz2Route(this);
  }

  static _Route? _instance;

  late final Biz1Route biz1;

  late final Biz2Route biz2;

  /// 当登录成功后调用
  ///
  /// `userName` user name of login user.
  ///
  Future<bool> login({
    final int? uid,
    required final String userName,
    final String userToken = 'good token',
    final int index = 0,
  }) =>
      ThrioNavigator.notify(
        url: url,
        name: 'login',
        params: {
          'uid': uid,
          'userName': userName,
          'userToken': userToken,
        },
        index: index,
      );

  Future<bool> logout({final int index = 0}) => ThrioNavigator.notify(
        url: url,
        name: 'logout',
        index: index,
      );
}
