// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import '../../types/people.dart';

class Flutter6Route extends NavigatorRouteLeaf {
  factory Flutter6Route(final NavigatorRouteNode parent) => _instance ??= Flutter6Route._(parent);

  Flutter6Route._(super.parent);

  static Flutter6Route? _instance;

  @override
  String get name => 'flutter6';

  Future<TPopParams> push<TParams, TPopParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorIntCallback? result,
  }) =>
      ThrioNavigator.push(
        url: url,
        params: params,
        animated: animated,
        result: result,
      );
}
