// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import '../../route.dart';
import 'flutter6.page.dart';

class Module with ThrioModule, ModulePageBuilder, ModuleRouteCustomHandler {
  factory Module() => _instance;

  Module._();

  static final _instance = Module._();

  @override
  String get key => 'flutter6';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (final settings) => Flutter6Page(
            moduleContext: moduleContext,
            params: settings.params,
            url: settings.url,
            index: settings.index,
          );

  @override
  void onRouteCustomHandlerRegister(final ModuleContext moduleContext) {
    registerRouteCustomHandler(
        'justascheme://open/home{?tab}',
        <Void>(
          final url,
          final queryParams, {
          final params,
          final animated = true,
          final result,
        }) async =>
            ThrioNavigator.push(
              url: root.biz1.flutter3.url,
              params: params,
              animated: animated,
              result: result,
            ));
    registerRouteCustomHandler(
        'anotherScheme://leaderboard/home{?hashId,product}',
        <Void>(
          final url,
          final queryParams, {
          final params,
          final animated = true,
          final result,
        }) async =>
            ThrioNavigator.push(
              url: root.biz1.flutter3.url,
              params: params,
              animated: animated,
              result: result,
            ));
  }
}
