// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//
// ignore_for_file: avoid_as

/// a struct description a people
///
class People {
  People({
    required this.name,
    required this.age,
    required this.sex,
  });

  factory People.fromMap(final Map<String, dynamic> json) =>
      People(name: json['name'] as String, age: json['age'] as int, sex: json['sex'] as String);

  final String name;

  final int age;

  final String sex;

  Map<String, dynamic> toMap() => <String, dynamic>{
        'name': name,
        'age': age,
        'sex': sex,
      };
}
