// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//
// ignore_for_file: avoid_as

/// 结构体的注释
///
class UserProfile {
  UserProfile({
    final int? uid = 2,
    required this.userName,
    final bool emailVerified = false,
    final bool mobileVerified = false,
    required this.userToken,
  })  : _uid = uid,
        _emailVerified = emailVerified,
        _mobileVerified = mobileVerified;

  factory UserProfile.fromMap(final Map<String, dynamic> json) => UserProfile(
      uid: json['uid'] as int?,
      userName: json['userName'] as String,
      emailVerified: json['emailVerified'] as bool? ?? false,
      mobileVerified: json['mobileVerified'] as bool? ?? false,
      userToken: json['userToken'] as String);

  int? _uid = 2;

  final String userName;

  bool _emailVerified = false;

  bool _mobileVerified = false;

  final String userToken;

  /// 字段的注释
  ///
  int? get uid => _uid;

  bool get emailVerified => _emailVerified;

  bool get mobileVerified => _mobileVerified;

  Map<String, dynamic> toMap() => <String, dynamic>{
        'userName': userName,
        'emailVerified': _emailVerified,
        'mobileVerified': _mobileVerified,
        'userToken': userToken,
      };
}
