// Copyright (c) 2022 bybit.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

class Flutter4Route extends NavigatorRouteLeaf {
  factory Flutter4Route(final NavigatorRouteNode parent) =>
      _instance ??= Flutter4Route._(parent);

  Flutter4Route._(final super.parent);

  static Flutter4Route? _instance;

  @override
  String get name => 'flutter4';

  Future<int> push<TParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorParamsCallback? poppedResult,
  }) =>
      ThrioNavigator.push(
        url: url,
        params: params,
        animated: animated,
        poppedResult: poppedResult,
      );
}
