// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter10/flutter10.route.dart';
import 'flutter2/flutter2.route.dart';
import 'flutter4/flutter4.route.dart';
import 'flutter6/flutter6.route.dart';
import 'flutter8/flutter8.route.dart';

class Biz2Route extends NavigatorRouteNode {
  factory Biz2Route(final NavigatorRouteNode parent) =>
      _instance ??= Biz2Route._(parent);

  Biz2Route._(super.parent);

  static Biz2Route? _instance;

  late final flutter2 = Flutter2Route(this);

  late final flutter4 = Flutter4Route(this);

  late final flutter6 = Flutter6Route(this);

  late final flutter8 = Flutter8Route(this);

  late final flutter10 = Flutter10Route(this);

  @override
  String get name => 'biz2';
}
