// Copyright (c) 2024 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_jsonable/flutter_jsonable.dart';
import 'package:flutter_thrio/flutter_thrio.dart';

import 'biz1/module.dart' as biz1;
import 'biz2/module.dart' as biz2;
import 'types/house.dart';
import 'types/people.dart';
import 'types/user_profile.dart';

class Module
    with
        ThrioModule,
        ModuleJsonDeserializer,
        ModuleJsonSerializer,
        ModuleJsonable,
        ModuleParamScheme {
  @override
  String get key => 'biz';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(biz1.Module(), moduleContext);
    registerModule(biz2.Module(), moduleContext);
  }

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme('intKeyRootModule');
    registerParamScheme('people');
  }

  @override
  void onJsonableRegister(final ModuleContext moduleContext) {
    registerJsonable<People>(JsonableBuilder<People>(
      (obj) => obj.toJson(),
      People.fromJson,
    ));
    registerJsonable<House>(JsonableBuilder<House>(
      (obj) => obj.toJson(),
      House.fromJson,
    ));
    registerJsonable<UserProfile>(JsonableBuilder<UserProfile>(
      (obj) => obj.toJson(),
      UserProfile.fromJson,
    ));
  }

  @override
  void onJsonSerializerRegister(final ModuleContext moduleContext) {
    registerJsonSerializer<People>((i) => i<People>().toJson());
    registerJsonSerializer<House>((i) => i<House>().toJson());
    registerJsonSerializer<UserProfile>((i) => i<UserProfile>().toJson());
  }

  @override
  void onJsonDeserializerRegister(final ModuleContext moduleContext) {
    registerJsonDeserializer(People.fromJson);
    registerJsonDeserializer(House.fromJson);
    registerJsonDeserializer(UserProfile.fromJson);
  }
}
