// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'biz1/biz1.route.dart';
import 'biz2/biz2.route.dart';

final biz = AppRoute();

class AppRoute extends NavigatorRouteNode {
  factory AppRoute() => _instance ??= AppRoute._();

  AppRoute._() : super.home();

  static AppRoute? _instance;

  late final biz1 = Biz1Route(this);

  late final biz2 = Biz2Route(this);

  @override
  String get name => 'biz';

  /// 当登录成功后调用
  ///
  /// `userName` user name of login user.
  ///
  Future<bool> login({
    final int? uid,
    required final String userName,
    final String userToken = 'good token',
  }) =>
      ThrioNavigator.notify(
        url: url,
        name: 'login',
        params: {
          'uid': uid,
          'userName': userName,
          'userToken': userToken,
        },
      );

  Future<bool> logout() => ThrioNavigator.notify(
        url: url,
        name: 'logout',
      );
}
