// Copyright (c) 2022 bybit.
//
// Do not edit this file.
//
// ignore_for_file: avoid_as

import 'package:flutter_thrio/flutter_thrio.dart';

typedef LogoutNotifyCallback = void Function();

class LogoutNotify extends NavigatorPageNotify {
  LogoutNotify({
    final super.key,
    required final LogoutNotifyCallback onNotify,
    required final super.child,
  }) : super(
          name: 'logout',
          onPageNotify: (final _) => onNotify(),
        );
}
