// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//
// ignore_for_file: avoid_as

import 'package:flutter_thrio/flutter_thrio.dart';

typedef Flutter1NotifyCallback = void Function({int intValue});

class Flutter1Notify extends NavigatorPageNotify {
  Flutter1Notify({
    super.key,
    required final Flutter1NotifyCallback onNotify,
    final int? intValue,
    required super.child,
  }) : super(
            name: 'flutter1',
            onPageNotify: (final params) =>
                onNotify(intValue: params['intValue'] as int),
            initialParams: intValue == null ? null : {'intValue': intValue});
}
