// Copyright (c) 2022 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

class Flutter7Route extends NavigatorRouteLeaf {
  factory Flutter7Route(final NavigatorRouteNode parent) => _instance ??= Flutter7Route._(parent);

  Flutter7Route._(super.parent);

  static Flutter7Route? _instance;

  @override
  String get name => 'flutter7';

  Future<int> push<TParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorParamsCallback? poppedResult,
  }) =>
      ThrioNavigator.push(
        url: url,
        params: params,
        animated: animated,
        poppedResult: poppedResult,
      );
}
