// Copyright (c) 2022 bybit.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

class Flutter2Route extends NavigatorRouteLeaf {
  factory Flutter2Route(final NavigatorRouteNode parent) =>
      _instance ??= Flutter2Route._(parent);

  Flutter2Route._(final super.parent);

  static Flutter2Route? _instance;

  @override
  String get name => 'flutter2';

  Future<int> push<TParams>({
    final TParams? params,
    final bool animated = true,
    final NavigatorParamsCallback? poppedResult,
  }) =>
      ThrioNavigator.push(
        url: url,
        params: params,
        animated: animated,
        poppedResult: poppedResult,
      );
}
